// Generated by CoffeeScript 1.10.0
(function() {
  var controller, initView;

  initView = function(ele) {
    return myCommonUITools.addDefaultButton(function() {
      return ele;
    }, function() {
      var goalEle, text;
      goalEle = $(this).parent().find('h1');
      if (goalEle.length === 0) {
        goalEle = $(this).parent().find('h3');
      }
      text = goalEle.text().trim();
      return myChromePlugTools.sendMsg("openYiTaoAndSearch", {
        searchWord: text
      });
    }, '打开一淘');
  };

  controller = new PageActionControllerZ();

  controller.add(new PageActionJQ(function() {
    if ($('.tb-detail-hd').length !== 0) {
      return $('.tb-detail-hd');
    }
    return $('#J_Title');
  }, function(ele) {
    return initView(ele);
  }));

  controller.doAction();

}).call(this);

//# sourceMappingURL=goodsPageAction.js.map
