// Generated by CoffeeScript 1.10.0
(function() {
  var controller;

  controller = new PageActionControllerZ();

  controller.add(new PageActionJQ(function() {
    return $('#J_searchIpt');
  }, function(ele) {
    ele.val(searchWord);
    return setTimeout(function() {
      return $('div.s-btn-container input').click();
    }, 1000);
  }));

  controller.doAction();

}).call(this);

//# sourceMappingURL=yiTaoPageAction.js.map
