// Generated by CoffeeScript 1.10.0
(function() {
  window.myChromePlugTools = {
    privateKeyID: 'PRIVATE_KEY_ID',
    sendMsg: function(key, data, tabID) {
      if (tabID == null) {
        tabID = false;
      }
      data[this.privateKeyID] = key;
      if (tabID) {
        chrome.tabs.sendMessage(tabID, data);
        return;
      }
      return chrome.extension.sendMessage(data);
    },
    onReceiveKey: function(key, callback, NoMsgID) {
      if (NoMsgID == null) {
        NoMsgID = false;
      }
      return this.onReceive([key], callback, NoMsgID);
    },
    onReceive: function(keys, callback, NoMsgID) {
      var me;
      if (NoMsgID == null) {
        NoMsgID = false;
      }
      me = this;
      return chrome.extension.onMessage.addListener(function(obj, sender) {
        if (NoMsgID || keys.indexOf(obj[me.privateKeyID]) !== -1) {
          return callback(obj, sender, obj[me.privateKeyID]);
        }
      });
    }
  };

}).call(this);

//# sourceMappingURL=myChromePlugTools.js.map
