// Generated by CoffeeScript 1.10.0
(function() {
  var openYiTao;

  openYiTao = function(searchWord) {
    return chrome.tabs.create({
      url: 'http://www.etao.com/'
    }, function(tab) {
      chrome.tabs.executeScript(tab.id, {
        code: "searchWord='" + searchWord + "'"
      });
      chrome.tabs.executeScript(tab.id, {
        file: 'async.js'
      });
      chrome.tabs.executeScript(tab.id, {
        file: 'jquery.min.js'
      });
      return chrome.tabs.executeScript(tab.id, {
        file: 'myLib.js'
      }, function() {
        return chrome.tabs.executeScript(tab.id, {
          file: 'yiTaoPageAction.js'
        });
      });
    });
  };

  myChromePlugTools.onReceiveKey("openYiTaoAndSearch", function(obj, sender, key) {
    return openYiTao(obj['searchWord']);
  });

}).call(this);

//# sourceMappingURL=background.js.map
